# Generated by Django 3.2.5 on 2021-07-13 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_activity_id'),
        ('main_app', '0004_proposal'),
    ]

    operations = [
    ]
