# Generated by Django 3.2.5 on 2021-07-13 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_merge_0004_alter_activity_id_0004_proposal'),
        ('main_app', '0005_remove_proposal_availability'),
    ]

    operations = [
    ]
