# Generated by Django 3.1.6 on 2021-07-14 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_activity_id'),
        ('main_app', '0005_remove_proposal_availability'),
    ]

    operations = [
    ]
