# Generated by Django 3.2.5 on 2021-07-13 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_remove_proposal_availability'),
        ('main_app', '0006_alter_proposal_id'),
    ]

    operations = [
    ]
