# Generated by Django 3.1.6 on 2021-07-14 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_merge_20210713_2252'),
        ('main_app', '0007_merge_20210713_2338'),
        ('main_app', '0006_merge_20210714_0035'),
    ]

    operations = [
    ]
