# Generated by Django 3.2.5 on 2021-07-14 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_merge_20210713_2252'),
        ('main_app', '0006_merge_20210714_0035'),
        ('main_app', '0007_merge_20210713_2338'),
    ]

    operations = [
    ]
