# Generated by Django 3.2.5 on 2021-07-14 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_merge_20210713_2252'),
        ('main_app', '0008_merge_20210714_0209'),
    ]

    operations = [
    ]
