# Generated by Django 3.2.5 on 2021-07-14 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_merge_20210714_0426'),
        ('main_app', '0009_merge_20210714_0225'),
    ]

    operations = [
    ]
