# Generated by Django 3.1.6 on 2021-07-14 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_activity_user'),
        ('main_app', '0008_merge_20210714_0426'),
    ]

    operations = [
    ]
