# Generated by Django 3.2.5 on 2021-07-14 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_merge_20210714_0917'),
        ('main_app', '0011_merge_20210714_1531'),
    ]

    operations = [
    ]
