# Generated by Django 3.2.5 on 2021-07-14 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_merge_20210714_1547'),
        ('main_app', '0012_merge_20210714_1556'),
    ]

    operations = [
    ]
