# Generated by Django 3.2.5 on 2021-07-14 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_auto_20210714_1706'),
        ('main_app', '0013_merge_20210714_1617'),
    ]

    operations = [
    ]
