# Generated by Django 3.2.5 on 2021-07-15 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_auto_20210714_1924'),
        ('main_app', '0015_auto_20210714_2238'),
    ]

    operations = [
    ]
