# Generated by Django 3.2.5 on 2021-07-15 02:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0017_auto_20210715_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_FK', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Attendees',
        ),
    ]
