# Generated by Django 3.2.5 on 2021-07-15 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_auto_20210715_0242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='duration',
        ),
        migrations.AddField(
            model_name='activity',
            name='stop',
            field=models.TimeField(default=1),
            preserve_default=False,
        ),
    ]
