# Generated by Django 3.1.6 on 2021-07-15 16:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0020_auto_20210715_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='attendees',
            field=models.ManyToManyField(related_name='attend_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
