# Generated by Django 3.2.5 on 2021-07-15 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0022_auto_20210715_1759'),
        ('main_app', '0022_auto_20210715_2152'),
    ]

    operations = [
    ]
