# Generated by Django 3.2.5 on 2021-07-16 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0023_merge_0022_auto_20210715_1759_0022_auto_20210715_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='category',
            field=models.CharField(choices=[('MU', 'MEETUP'), ('OD', 'OUTDOORS'), ('SP', 'SPORTS'), ('DR', 'DRINKS'), ('ML', 'MEAL'), ('PR', 'PROFESSIONAL'), ('OT', 'OTHER')], default='MU', max_length=2),
        ),
    ]
